/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TrackerRunnable */

#ifndef _Included_TrackerRunnable
#define _Included_TrackerRunnable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TrackerRunnable
 * Method:    doTracker
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TrackerRunnable_doTracker
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
