/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_unb_unbiquitous_ubiquitos_uos_driver_UserDriver_TrackerRunnale */

#ifndef _Included_br_unb_unbiquitous_ubiquitos_uos_driver_UserDriver_TrackerRunnale
#define _Included_br_unb_unbiquitous_ubiquitos_uos_driver_UserDriver_TrackerRunnale
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_unb_unbiquitous_ubiquitos_uos_driver_UserDriver_TrackerRunnale
 * Method:    doTracker
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_unb_unbiquitous_ubiquitos_uos_driver_UserDriver_00024TrackerRunnable_doTracker
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

/* Header for class br_unb_unbiquitous_ubiquitos_uos_driver_UserDriver */

#ifndef _Included_br_unb_unbiquitous_ubiquitos_uos_driver_UserDriver
#define _Included_br_unb_unbiquitous_ubiquitos_uos_driver_UserDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_unb_unbiquitous_ubiquitos_uos_driver_UserDriver
 * Method:    stopTracker
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_unb_unbiquitous_ubiquitos_uos_driver_UserDriver_stopTracker
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

